version: 0.0
os: linux
# ORIGINAL
#files:
#  - source: /index.html
#    destination: /var/www/html/
# END OF ORIGINAL
# trying custom files and destination below. Deploying to single server this time.
files:
  - source: /
    destination: /mnt/
# end of custom script
# option to run scripts below
#hooks:
#  BeforeInstall:
#    - location: scripts/install_dependencies
#      timeout: 300
#      runas: root
#    - location: scripts/start_server
#      timeout: 300
#      runas: root
#  ApplicationStop:
#    - location: scripts/stop_server
#      timeout: 300
#      runas: root

